---
title: "Gallery DataViz R and Python"
author: "Juliette Bassnagel & Pauline Olivier"
date: "03/03/2020"
output:
  html_document:
    toc: true
    toc_float: true
    theme: readable
    highlight: tango
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library('reticulate')

# Pauline
# use_python("/usr/local/anaconda3/envs/dataviz/bin/python") 

# Juliette
# use_python("/Users/juliette.bassnagel/anaconda3/envs/gallery/bin/python") 
use_python("/Users/juliette.bassnagel/anaconda3/bin/python")

# Pauline
# use_condaenv(condaenv = "dataviz", conda = "/usr/local/anaconda3/bin/conda")

# Juliette
use_condaenv(condaenv = "gallery", conda = "/Users/juliette.bassnagel/anaconda3/bin/conda")
```

```{python, echo=FALSE}
import seaborn as sns
df = sns.load_dataset('tips')
import matplotlib.pyplot as plt
plt.style.use('ggplot')
```


### Boxplot
**Python**
```{python}
sns.boxplot(x="day", y="total_bill", hue="smoker", data=df)
```

**R**

